Ability to assume a specific role
mgk/s3-plugin pull request #7
Opened 2017-03-13 06:36 UTC by marcin-caban

Plus a bug fix in S3Download (to use the defined client).

2017-03-13 07:11 UTC, marcin-caban commented
Apparently travis configuration is broken, missing AWS credentials.

I've built and tested it locally with role set, it works.

Could you, please, release a new version with my change? 

Thanks in advance.

Cheers
Marcin

2017-04-10 01:18 UTC, marcin-caban commented
@mgk Could you have a look on this?

2017-05-21 22:14 UTC, mgk commented
Sorry for delay. Looking at it now.

2017-05-21 22:56 UTC, mgk requested changes
LGTM otherwise. Build succeeds for me locally so I expect once merged the Travis build will succeed also.

2017-05-21 22:56 UTC, mgk commented on src/main/groovy/com/github/mgk/gradle/S3Plugin.groovy
> +        if (s3Client) {
I have run into issues reusing the `s3Client` object (I seem to recall it expiring or becoming invalid after a certain period of time) so I create it for each operation.

If you really want s3Client reuse, please put that in a separate PR and make it configurable via an environment variable.

2019-12-19 20:45 UTC, mgk commented
Appears abandoned. Closing. Please reopen if needed (and not feedback above). Thanks.

2019-12-19 20:45 UTC, closed without merging